config/routes.rb
Rails.application.routes.draw do




  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'searchs/search'
  root 'customers/products#top'
  get 'customers/products/about' => 'customers/products#about'
  get 'customers/products/favorite' => 'customers/products#favorite'

  get 'customers/mypage' => 'customers#mypage'
  get 'customers/withdraw' => 'customers#withdraw'
  put 'customers/withdraw' => 'customers#withdraw_update'
  get 'customers/fix' => 'customers#fix'
  patch 'customers/fix' => 'customers#fix_update'
  put 'customers/fix' => 'customers#fix_update'



  namespace :customers do
    resources :products, only: [:index, :show] do
      resources :post_comments, only: [:create, :destroy] #do~end
      resource :favorites, only:[:create, :destroy]
    end
    resources :product_genres, only: [:show]
    resources :cart_products, only: [:index, :update, :destroy, :create]# showをindexに変更
    delete 'cart_products' => 'cart_products#destroy_all', as:'destroy_all'

    get 'order_lists/input' => 'order_lists#input'# 順番変更とcustomers/削除
    get 'order_lists/confirm' => 'order_lists#confirm'# 追加
    get 'order_lists/thanks' => 'order_lists#thanks'# 順番変更とcustomers/削除
    resources :order_lists, only: [:index, :show, :create]# 順番変更

    resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]

  end

    get 'admins/searchs' => 'admins/searchs#search'

  namespace :admins do
    get 'top' => 'order_lists#top'

    resources :customers, only: [:index, :show, :edit, :update]

    resources :order_lists, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    resources :products, only: [:index, :show, :edit, :update, :create, :new]

    resources :product_genres, only: [:index, :edit, :update, :create]

    resources :payment_methods, only: [:index, :edit, :update, :create]

    resources :postages, only: [:index,:edit, :update, :create]
  end

end

app/models/order_list.rb
class OrderList < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum status:{waitingpayment:0, paymentok:1, making:2, preparation:3, finishshipping:4}
   enum making_status:{cannotmaking:0, waitmaking:1, nowmaking:2, finishmaking:3}
  # enum status:{"入金待ち":0, "入金確認":1, "製作中":2, "発送準備中":3, "発送済み":4}
  # enum payment_method:{クレジットカード:0, 銀行振込:1}
  # enum status:{クレジットカード:0, 銀行振込:1}

  def sum_price
  	total_price + shipping_fee
  end

end

app/controllers/admins/order_lists_controller.rb
class Admins::OrderListsController < ApplicationController

	before_action :authenticate_admin!

	def top
		@order_lists = OrderList.where("created_at >= ?", Time.zone.now.beginning_of_day)
	end

	def index
		@order_lists = OrderList.all.order(id: "DESC")
	end

	def show
		@order_list = OrderList.find(params[:id])
	end

	def update
		@order_list = OrderList.find(params[:id])
		@order_list.update(order_list_params)
		if @order_list.status == "paymentok"
			@order_list.order_details.each do |order_detail|
				order_detail.update_attributes(making_status: "waitmaking")
			end
		end
		redirect_back(fallback_location: root_path)
	end

	private

	def order_list_params
		params.require(:order_list).permit(:status)
	end

end

app/controllers/customers/order_lists_controller.rb
class Customers::OrderListsController < ApplicationController

     before_action :authenticate_customer!# ログインしているユーザーのみ入れる

  def index #注文履歴一覧
    # @order_list = OrderList.new
    # @order_lists = OrderList.where(customer_id: current_customer.id) #ログインしているユーザーの注文履歴のみ表示
    @order_lists = current_customer.order_lists.order(id: "DESC") #has_many :order_listsでcustomerとアソシエーションされているため呼び出せる。
  end

  def show #注文履歴詳細
    @order_list = OrderList.find(params[:id])
  end

  def input
    @order_list = OrderList.new
  end

  def confirm
    @cart_products = current_customer.cart_products
    @postage = Postage.find(1)

    if params[:order_list][:address_method] == "self_address"
       payment_method = order_list_params[:payment_method]
              postal_code = current_customer.postal_code
              address = current_customer.address
              shipping_name = current_customer.name_sei + current_customer.name_mei
# session[:input] = {"payment": params[:order_list][:payment_method], "postal_code": current_customer.postal_code, "address": current_customer.address, "name": current_customer.name_sei + current_customer.name_mei}
    elsif params[:order_list][:address_method] == "registered_address"
          payment_method = order_list_params[:payment_method]
            a = ShippingAddress.find(params[:select].to_i) #ShippingAddressのidをfindで見つけてaに入れている。
              postal_code = a.postal_code
              address = a.address
              shipping_name = a.name
# session[:input] = {"payment": params[:order_list][:payment_method], "postal_code": a.postal_code, "address": a.address, "name": a.name }
    elsif params[:order_list][:address_method] == "new_address"
          payment_method = order_list_params[:payment_method]
              postal_code = order_list_params[:postal_code]
              address = order_list_params[:address]
              shipping_name = order_list_params[:shipping_name]
              @shipping_address = ShippingAddress.new(shipping_address_params)
              @shipping_address.customer_id = current_customer.id
              @shipping_address.save
    end
     @order_list = OrderList.new(payment_method: payment_method, postal_code: postal_code, address: address, shipping_name: shipping_name)



    # バリデーションのためのif文
    if params[:order_list][:address_method] == "self_address" && current_customer.postal_code.present? && current_customer.address.present? && payment(params[:order_list][:payment_method])
          render :confirm
    elsif params[:order_list][:address_method] == "registered_address" && @order_list.present? && payment(params[:order_list][:payment_method]) #registered_addressを選択してかつ@order_listに情報が入っておりかつ"支払い方法"を選択していない場合
          render :confirm
    elsif params[:order_list][:address_method] == "new_address" && params[:shipping_address][:postal_code].present? && params[:shipping_address][:address].present? && params[:shipping_address][:name].present? && payment(params[:order_list][:payment_method])
          render :confirm
    else
       redirect_to request.referer # 遷移前のURLを取得
    end
  end

  def create
    @order_list = OrderList.new(order_list_params)
    # OrderList.new(order_list_params)=受け取る箱（saveがされていない）
    @cart_products = current_customer.cart_products

      @order_list.customer_id = current_customer.id #会員id
    @cart_products.each do |cart_product| # 清算後のマイバックに入れている商品をorder_detailからcart_productを通して持ってくる
      order_detail = @order_list.order_details.new # order_listの主idはnewに入っている
      order_detail.product_id = cart_product.product_id #商品
      order_detail.price = cart_product.product.price * 1.1 #商品の価格
      order_detail.number = cart_product.number # 商品の個数
    end
    if @order_list.save
    # @order_listには１つのレコードが保存
    @cart_products.destroy_all #ログインユーザーのカートを定義、全て削除
    redirect_to customers_order_lists_thanks_path
    else
      # @order_list.errors.full_messages.each do |msg|
      #   p msg #p = プリント
      # end
      redirect_to request.referer # 遷移前のURLを取得
    end
  end

  def thanks
  end

  private
  def order_list_params
    params.require(:order_list).permit(:shipping_fee, :customer_id, :total_price, :status, :payment_method, :shipping_name, :postal_code, :address)
  end
  def shipping_address_params
    params.require(:shipping_address).permit(:name, :postal_code, :address)
  end

  def payment(pay)
    if pay == "支払い方法"
      false
    else
      true
    end
  end
end

app/helpers/admins/order_lists_helper.rb
module Admins::OrderListsHelper
	def converting_to_jpy(price)
    	"#{price.to_s(:delimited, delimiter: ',')}円"
	end
end

app/helpers/customers/order_lists_helper.rb
module Customers::OrderListsHelper
    def converting_to_jpy(price)
       "#{price.to_s(:delimited, delimiter: ',')}円"
	end
end

app/views/admins/order_lists/index.html.erb
<div class="midasi">
	<h3 class="midasitext">注文履一覧</h3>
</div>

<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>購入日時</th>
			<th>購入者</th>
			<th>注文数</th>
			<th>注文ステータス</th>
		</tr>
	</thead>

	<tbody>
		<% @order_lists.each do |order_list| %>
		<tr>
			<td><a href="<%= admins_order_list_path(order_list.id) %>"><%= l order_list.created_at%></a></td>
			<td><%= order_list.customer.name_sei%><%= order_list.customer.name_mei%></td>
			<td><%= order_list.order_details.all.sum(:number) %></td>
			<td><%= order_list.status_i18n%></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admins/order_lists/show.html.erb
<div class="container">
<div class="midasi">
	<h3 class="midasitext">注文履歴詳細</h3>
</div>

<div class="customer_contents">
		<div class="admin_naiyou">
			<div class="admin_c_label"><p>購入者</p></div>
			<a href="<%= admins_customer_path(@order_list.customer.id) %>">
			<%= @order_list.customer.name_sei %><%= @order_list.customer.name_mei %></a>
		</div>
		<div class="admin_naiyou">
			<div class="admin_c_label"><p>宛名</p></div>
				<%= @order_list.shipping_name %>
			<div class="admin_c_label"><p>配送先</p></div>
				<%= @order_list.postal_code.insert(3, '-') %><%= @order_list.address %>
		</div>
		<div class="admin_naiyou">
			<div class="admin_c_label"><p>支払方法</p></div>
			<%= @order_list.payment_method %>
		</div>
		<div class="admin_naiyou">
			<div class="admin_c_label"><p>注文ステータス</p></div>
			<%= @order_list.status_i18n %>
			<div class="orderstatus">
				<%= form_for @order_list, url: admins_order_list_path(@order_list.id) do |f| %>
						<%= f.select :status,options_for_select(OrderList.statuses.keys.map {|k| [I18n.t("enums.order_list.status.#{k}"), k]},:selected => @order_list.status) %>
					<div class="o_button">
  						<%= f.submit '変更' %>
  					</div>
  				<% end %>
  			</div>
		</div>
</div>

<div class="o_table">
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>商品名</th>
			<th>単価（税込み）</th>
			<th>数量</th>
			<th>小計</th>
			<th>制作ステータス</th>
		</tr>
	</thead>

	<tbody>
		<% @order_list.order_details.each do |order_detail| %>
		<tr>
			<td><%= order_detail.product.name %></td>
			<td><%= converting_to_jpy(order_detail.price) %></td>
			<td><%= order_detail.number %></td>
			<td><%= converting_to_jpy(order_detail.sum_price) %></td>
			<td><%= order_detail.making_status_i18n %></td>
			<%= form_for order_detail, url: admins_order_detail_path(order_detail.id) do |f| %>
			<td><%= f.select :making_status,options_for_select(OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]},:selected => order_detail.making_status) %></td>
			<td><%= f.submit '変更' %></td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

<div class="admin_total">
	<div class="admin_total_naiyou">
		<div class="admin_label"><p>商品合計</p></div>
			<%= converting_to_jpy(@order_list.total_price) %>
	</div>
	<div class="admin_total_naiyou">
		<div class="admin_label"><p>送料</p></div>
			<%= converting_to_jpy(@order_list.shipping_fee) %>
	</div>
	<div class="admin_total_naiyou">
		<div class="admin_label"><p>請求金額合計</p></div>
			<%= converting_to_jpy(@order_list.sum_price) %>
	</div>
</div>
</div>

app/views/admins/order_lists/top.html.erb
<div class="midasi">
	<h3 class="midasitext">管理者画面</h3>
</div>

<div class="ordercounts_text">
	<p>本日の注文件数</p>
</div>

<div class="ordercounts">
<%= link_to "#{@order_lists.count} 件", admins_order_lists_path %>
</div>