config/routes.rb
Rails.application.routes.draw do




  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'searchs/search'
  root 'customers/products#top'
  get 'customers/products/about' => 'customers/products#about'
  get 'customers/products/favorite' => 'customers/products#favorite'

  get 'customers/mypage' => 'customers#mypage'
  get 'customers/withdraw' => 'customers#withdraw'
  put 'customers/withdraw' => 'customers#withdraw_update'
  get 'customers/fix' => 'customers#fix'
  patch 'customers/fix' => 'customers#fix_update'
  put 'customers/fix' => 'customers#fix_update'



  namespace :customers do
    resources :products, only: [:index, :show] do
      resources :post_comments, only: [:create, :destroy] #do~end
      resource :favorites, only:[:create, :destroy]
    end
    resources :product_genres, only: [:show]
    resources :cart_products, only: [:index, :update, :destroy, :create]# showをindexに変更
    delete 'cart_products' => 'cart_products#destroy_all', as:'destroy_all'

    get 'order_lists/input' => 'order_lists#input'# 順番変更とcustomers/削除
    get 'order_lists/confirm' => 'order_lists#confirm'# 追加
    get 'order_lists/thanks' => 'order_lists#thanks'# 順番変更とcustomers/削除
    resources :order_lists, only: [:index, :show, :create]# 順番変更

    resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]

  end

    get 'admins/searchs' => 'admins/searchs#search'

  namespace :admins do
    get 'top' => 'order_lists#top'

    resources :customers, only: [:index, :show, :edit, :update]

    resources :order_lists, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    resources :products, only: [:index, :show, :edit, :update, :create, :new]

    resources :product_genres, only: [:index, :edit, :update, :create]

    resources :payment_methods, only: [:index, :edit, :update, :create]

    resources :postages, only: [:index,:edit, :update, :create]
  end

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

	before_action :authenticate_admin!

	def index
		@customers = Customer.all
	end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
			redirect_to admins_customer_path(@customer.id)
		else
			render :edit
		end
	end

	private

	def customer_params
		params.require(:customer).permit(:name_sei, :name_mei, :yomi_sei, :yomi_mei, :postal_code, :address, :tell, :email, :status)
	end

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController

	before_action :authenticate_admin!

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to admins_product_path(@product.id)
		else
			render :new
		end
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to admins_product_path(@product.id)
		else
			render :edit
		end
	end

	private

	def product_params
		params.require(:product).permit(:name, :description, :price, :picture, :sales_status, :product_genre_id)
	end

end

app/controllers/customers/cart_products_controller.rb
class Customers::CartProductsController < ApplicationController

   before_action :authenticate_customer!# ログインしているユーザーのみ入れる

  def index
    @cart_product = CartProduct.new
  	@cart_products = current_customer.cart_products # current_customerの商品のみ表示
    # ログインしていないユーザーもカートに追加できるようにする
  end

  def create
    # 顧客が同じ商品をカートに入れているか確認
    @cart_product = CartProduct.find_by(customer_id: current_customer.id, product_id: cart_product_params[:product_id])
    # あれば
    if @cart_product.present?
      # 更新
       result = @cart_product.number + cart_product_params[:number].to_i #cart_product_params[:number]はハッシュで入っている（例：{ number: 1, product_id: 2, hoge: 'hoge', hige: 'hige' }）
       @cart_product.number = result
    # 無ければ
    else
      # 新規作成
      @cart_product = CartProduct.new(cart_product_params)
      @cart_product.customer_id = current_customer.id #customersの情報
    end

    if @cart_product.save
    # @cart_productには１つのレコードが保存
      redirect_to customers_cart_products_path
    # (@cart_product.id)で保存されたから次のページに飛べるとべる
    else
      redirect_to request.referer # 遷移前のURLを取得
    end
  end

  def update
    @cart_product = CartProduct.find(params[:id]) #idの箇所はURLと同じ記述
    @cart_product.update(cart_product_params)
    redirect_to request.referer # 遷移前のURLを取得
  end

  def destroy
  	@cart_product = CartProduct.find(params[:id]) #idの箇所はURLと同じ記述
    @cart_product.destroy
    redirect_to request.referer # 遷移前のURLを取得
  end

  def destroy_all #destroy_allカートを空にする為
    @cart_products = current_customer.cart_products #ログインユーザーのカートを定義
    @cart_products.destroy_all #全て削除
    redirect_to request.referer # 遷移前のURLを取得
  end

private

  def cart_product_params
    params.require(:cart_product).permit(:number, :product_id) #:product_idでどの商品か判断している。paramsはformから送られてきたのを許可するための記述。
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController

    before_action :authenticate_customer!

	def create
        @product = Product.find(params[:product_id])
        @favorite = Favorite.new(product_id: @product.id)
        @favorite.customer_id = current_customer.id
        @favorite.save
        redirect_back(fallback_location: root_path)
        end

    def destroy
        @product = Product.find(params[:product_id])
        @favorite = Favorite.find_by(product_id: @product.id)
        @favorite.customer_id = current_customer.id
        @favorite.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/order_lists_controller.rb
class Customers::OrderListsController < ApplicationController

     before_action :authenticate_customer!# ログインしているユーザーのみ入れる

  def index #注文履歴一覧
    # @order_list = OrderList.new
    # @order_lists = OrderList.where(customer_id: current_customer.id) #ログインしているユーザーの注文履歴のみ表示
    @order_lists = current_customer.order_lists.order(id: "DESC") #has_many :order_listsでcustomerとアソシエーションされているため呼び出せる。
  end

  def show #注文履歴詳細
    @order_list = OrderList.find(params[:id])
  end

  def input
    @order_list = OrderList.new
  end

  def confirm
    @cart_products = current_customer.cart_products
    @postage = Postage.find(1)

    if params[:order_list][:address_method] == "self_address"
       payment_method = order_list_params[:payment_method]
              postal_code = current_customer.postal_code
              address = current_customer.address
              shipping_name = current_customer.name_sei + current_customer.name_mei
# session[:input] = {"payment": params[:order_list][:payment_method], "postal_code": current_customer.postal_code, "address": current_customer.address, "name": current_customer.name_sei + current_customer.name_mei}
    elsif params[:order_list][:address_method] == "registered_address"
          payment_method = order_list_params[:payment_method]
            a = ShippingAddress.find(params[:select].to_i) #ShippingAddressのidをfindで見つけてaに入れている。
              postal_code = a.postal_code
              address = a.address
              shipping_name = a.name
# session[:input] = {"payment": params[:order_list][:payment_method], "postal_code": a.postal_code, "address": a.address, "name": a.name }
    elsif params[:order_list][:address_method] == "new_address"
          payment_method = order_list_params[:payment_method]
              postal_code = order_list_params[:postal_code]
              address = order_list_params[:address]
              shipping_name = order_list_params[:shipping_name]
              @shipping_address = ShippingAddress.new(shipping_address_params)
              @shipping_address.customer_id = current_customer.id
              @shipping_address.save
    end
     @order_list = OrderList.new(payment_method: payment_method, postal_code: postal_code, address: address, shipping_name: shipping_name)



    # バリデーションのためのif文
    if params[:order_list][:address_method] == "self_address" && current_customer.postal_code.present? && current_customer.address.present? && payment(params[:order_list][:payment_method])
          render :confirm
    elsif params[:order_list][:address_method] == "registered_address" && @order_list.present? && payment(params[:order_list][:payment_method]) #registered_addressを選択してかつ@order_listに情報が入っておりかつ"支払い方法"を選択していない場合
          render :confirm
    elsif params[:order_list][:address_method] == "new_address" && params[:shipping_address][:postal_code].present? && params[:shipping_address][:address].present? && params[:shipping_address][:name].present? && payment(params[:order_list][:payment_method])
          render :confirm
    else
       redirect_to request.referer # 遷移前のURLを取得
    end
  end

  def create
    @order_list = OrderList.new(order_list_params)
    # OrderList.new(order_list_params)=受け取る箱（saveがされていない）
    @cart_products = current_customer.cart_products

      @order_list.customer_id = current_customer.id #会員id
    @cart_products.each do |cart_product| # 清算後のマイバックに入れている商品をorder_detailからcart_productを通して持ってくる
      order_detail = @order_list.order_details.new # order_listの主idはnewに入っている
      order_detail.product_id = cart_product.product_id #商品
      order_detail.price = cart_product.product.price * 1.1 #商品の価格
      order_detail.number = cart_product.number # 商品の個数
    end
    if @order_list.save
    # @order_listには１つのレコードが保存
    @cart_products.destroy_all #ログインユーザーのカートを定義、全て削除
    redirect_to customers_order_lists_thanks_path
    else
      # @order_list.errors.full_messages.each do |msg|
      #   p msg #p = プリント
      # end
      redirect_to request.referer # 遷移前のURLを取得
    end
  end

  def thanks
  end

  private
  def order_list_params
    params.require(:order_list).permit(:shipping_fee, :customer_id, :total_price, :status, :payment_method, :shipping_name, :postal_code, :address)
  end
  def shipping_address_params
    params.require(:shipping_address).permit(:name, :postal_code, :address)
  end

  def payment(pay)
    if pay == "支払い方法"
      false
    else
      true
    end
  end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/post_comments_controller.rb
class Customers::PostCommentsController < ApplicationController
 before_action :authenticate_customer!# ログインしているユーザーのみ入れる
 #before_action :authenticate_admin!

 def create
   @product = Product.find(params[:product_id])
   @post_comment = current_customer.post_comments.new(post_comment_params)
   @post_comment.product_id = @product.id
  if @post_comment.save
  	flash[:notice] = "success!"
    redirect_to request.referer#成功
  else
  	@product_new = CartProduct.new #formforで使うための空のモデル(空の箱),CartProductのコントローラーに送る。
    @genres = ProductGenre.only_active
  	render 'customers/products/show' #失敗
  end
 end



 def destroy
   comment = PostComment.find(params[:id])
   comment.destroy
   redirect_back(fallback_location: root_path)
 end


 private
 def post_comment_params
 	params.require(:post_comment).permit(:comment)
 end
end

app/controllers/customers/product_genres_controller.rb
class Customers::ProductGenresController < ApplicationController
	def show
		@products = Product.where(product_genre_id: params[:id]).page(params[:page]).per(8)
		@genres = ProductGenre.where(is_valid: true)
		@genre = ProductGenre.find(params[:id])
	end
end

app/controllers/customers/products_controller.rb
class Customers::ProductsController < ApplicationController

def top
 @products = Product.where(sales_status: "recommend").page(params[:page]).per(3)
 @genres = ProductGenre.only_active
end

def about
end

def favorite
	@products = current_customer.favorite_products.page(params[:page]).per(8)
	@genres = ProductGenre.only_active
end

def index
 @product = Product.new
 @products = Product.only_active.page(params[:page]).per(8)
#@products = []

# Product.all.each do |product|
#	if product.product_genre.is_valid #== true
#	 	@products << product
#	end
#end

 @genres = ProductGenre.only_active
end

def show
 @product = Product.find(params[:id])
 @product_new = CartProduct.new #formforで使うための空のモデル(空の箱),CartProductのコントローラーに送る。
 @post_comment = PostComment.new #商品へのコメント
 @genres = ProductGenre.only_active

end

def create
end


  private

  def product_params
  	params.require(:product).permit(:product_genre_id, :name, :description, :price, :picture_id, :sales_status, :customer_id)
  end

end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_sign_up_path_for(resource)
    root_path
  end

  def reject_user
     @user = Customer.find_by(email: params[:customer][:email].downcase)
     if @user
       if (@user.valid_password?(params[:customer][:password]) && (@user.active_for_authentication? == false))
         flash[:error] = "退会済みです。"
         redirect_to new_customer_registration_path
       end
     else
       flash[:error] = "必須項目を入力してください。"
     end
   end

  private
  def sign_up_params
    params.require(:customer).permit(:name_sei, :name_mei, :yomi_sei, :yomi_mei, :postal_code, :address, :tell, :password, :email)
  end



end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
	def converting_to_jpy(price)
    	"#{price.to_s(:delimited, delimiter: ',')}円"
	end
end

app/views/customers/products/favorite.html.erb
<div class="container">
  <div class="row">
  
  <%= render 'layouts/sidebar', genres: @genres %>

    <div class="col-xs-10">
     <div class="main-body">
      <div class="row">
          <h2 class="product_index_title">お気に入り商品一覧<i class="fas fa-cookie-bite"></i></h2><p class="count"><%= link_to "全#{@products.count}件" %></p>
          <% @products.each do |product| %>
          <div class="col-md-3">
             <div>
              　<div class="product-page">
                <%= link_to customers_product_path(product.id) do %>
                  <%= attachment_image_tag product, :picture, format:'jpeg', size:"150x150" %><br>
                   <div class="favorite">
                    <% if current_customer %>
                      <% if product.favorited_by?(current_customer) %>
                        <%= link_to customers_product_favorites_path(product), method: :delete do %>
                          <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                          <%= product.favorites.count %>
                        <% end %>
                      <% else %>
                        <%= link_to customers_product_favorites_path(product), method: :post do %>
                          <i class="fa fa-heart-o" aria-hidden="true"></i>
                          <%= product.favorites.count %>
                        <% end %>
                      <% end %>
                    <% else %>
                      <i class="fa fa-heart-o" aria-hidden="true"></i>
                      <%= product.favorites.count %>
                    <% end %>
                    </div>
                  <div class="product_price1"><%= product.name %><br></div>
                  <p class="product_price2"><%= product.price_with_tax(product.price) %>円</p><br>
                </div>
                <% end %>
             </div>
           </div>
         <% end %>
       </div>
       <div class="pagepage">

　　　　 <%#= paginate @products %>
　　　　
       </div>
     </div>
     </div>
  </div>
</div>

app/views/customers/products/index.html.erb
<div class="container">
  <div class="row">
  
  <%= render 'layouts/sidebar', genres: @genres %>

    <div class="col-xs-10">
     <div class="main-body">
      <div class="row">
          <h2 class="product_index_title">商品一覧<i class="fas fa-cookie-bite"></i></h2><p class="count"><%= link_to "全#{Product.all.count}件" %></p>
          <% @products.each do |product| %>
          <div class="col-md-3">
             <div>
              　<div class="product-page">
                <%= link_to customers_product_path(product.id) do %>
                  <%= attachment_image_tag product, :picture, format:'jpeg', size:"150x150" %><br>
                  <div class="product_price1"><%= product.name %><br></div>
                  <p class="product_price2"><%= product.price_with_tax(product.price) %>円</p><br>
                </div>
                <% end %>
             </div>
           </div>
         <% end %>
       </div>
       <div class="pagepage">

　　　　 <%= paginate @products %>
　　　　
       </div>
     </div>
     </div>
  </div>
</div>

     

app/views/customers/products/show.html.erb
<div class="container">
  <div class="row">

     <%= render 'layouts/sidebar', genres: @genres %>

    <div class="product_show">
        <div class="col-xs-10">
           <div class="top-body">
                <%= link_to @product_path do %>
                <% end %>
            <p class="product-image">
                   <%= attachment_image_tag @product, :picture, format:'jpeg', size:"250x250" %>
            </p>
                <div class="product-text">
                   <div class="favorite">
                      <% if current_customer %>
                        <% if @product.favorited_by?(current_customer) %>
                          <%= link_to customers_product_favorites_path(@product), method: :delete do %>
                           <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                             <%= @product.favorites.count %>
                          <% end %>
                        <% else %>
                           <%= link_to customers_product_favorites_path(@product), method: :post do %>
                             <i class="fa fa-heart-o" aria-hidden="true"></i>
                             <%= @product.favorites.count %>
                           <% end %>
                        <% end %>
                        <% else %>
                             <i class="fa fa-heart-o" aria-hidden="true"></i>
                             <%= @product.favorites.count %>
                        <% end %>
                    </div>
                        <p class="product-title"><%= @product.name %><br></p>
                        <p class="product-description"><%= @product.description %><br></p>
                        <p class="product-price">¥<%= @product.price_with_tax(@product.price) %>(税込)</p>
                </div>

                <div class="col-xs-10">

                <% if current_customer %><!--  ログインしているユーザーを指定（ログインしていない場合何も表示しない） -->
                    <% if @product.sales_status == "soldout" %><!--  整数でいじれない -->
                          <div class="cart_product">
                            <p>この商品は売り切れです。</p>
                    <% else %>
                        <%= form_for @product_new, url: customers_cart_products_path, method: :POST do |f| %>
                              <%= f.select :number,[1,2,3,4,5,6,7,8,9,10], :pronpt => "個数選択", class: 'sentaku' %>
                              <%= f.hidden_field :product_id, :value => @product.id %>
                    <!-- 商品のidをカート商品idに入れる -->
                              <%= f.submit "カートに入れる", class:"btn btn-primary" %><br>
                    <!-- method: :POSTはPOSTに飛ぶための記述 -->
                    <% end %>
                    <% end %>
                          </div>
                <% end %>
                </div>

            </div>
        </div>
    </div>



<!-- コメント表示部分 -->


   <div class="voicee">


    <% if @post_comment.errors.any? %>
        <div class="alert alert-warning">
             <ul>
               <h2><%= @post_comment.errors.count %> errors prohibited this book from being saved:</h2>
                 <% @post_comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
             </ul>
                <% end %>
        </div>
    <% end %>

      <h4 class="voice"> みんなの声<i class="fas fa-comments"></i></h4>
          <% @product.post_comments.each do |post_comment| %>
             <div class="comment_text">
                <%= post_comment.comment %>
                  <% if post_comment.customer == current_customer %>
                    <%= link_to '', customers_product_post_comment_path(@product, post_comment), method: :delete, class:"fas fa-trash fa trash_black " %>
                  <% end %>
          <% end %>
            </div>
   </div>

 <!-- コメント表示部分 -->

 <!-- コメント入力フォーム -->
    <div class="form_comment">
       <%= form_for [@product, @post_comment], url:customers_product_post_comments_path(@product) do |f| %>
            <div class="text_comment">
               <%= f.text_area :comment, rows:'3', class:"form-control comment_form", placeholder: "コメント"%>
            </div>
                <div class="submit_comment">
                   <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
                   <i class="far fa-comments"></i> コメントする
                   <% end %>
                </div>
                  <% end %>
    
    </div>
    <!-- コメント入力フォーム -->
  
  </div>
</div>

app/views/customers/products/top.html.erb
<div class="container">
  <div class="row">
<%= render 'layouts/sidebar', genres: @genres %>
    <div class="col-xs-10">
     <div class="main-body">
        
        <!-- <div class="main-visual">
        　<p class="main-text">
        	ようこそ、NaganoCakeへ！<br>
        	このサイトは、ケーキ販売のECサイトになります。<br>
        	会員でない方も商品の閲覧はできますが、<br>
        	購入には会員登録が必要になります。<br>
          </p>
        </div> -->

        <div class="container1"> <!-- jQuery版 -->
            <div id="theTarget">
              <div class="cake1"></div>
              <div class="cake2"></div>
              <div class="cake3"></div>
              <div class="cake4"></div>
              <div class="cake5"></div>
            </div>
              <p class="main-text1 box" id="js-target">
                このサイトは製作者が<br>小学校でこころのノートを読んでいないため、<br>
                他人を傷つける表現や、<br>
                不適切な内容が含まれております<br>
                予めご了承いただきますようよろしくお願いします<br>
                ばーかばーか
              </p>
        </div>
　　　
   　<h3 class="osusume"><i class="fas fa-star"></i>オヌヌメ<i class="fas fa-star"></i></h3>

          <% @products.each do |product| %>
          <div class="col-md-3">
             <div>
              　<div class="product-page">
                <%= link_to customers_product_path(product.id) do %>
                  <%= attachment_image_tag product, :picture, format:'jpeg', size:"200x200" %><br>
                  <div class="favorite">
                  <% if current_customer %>
                    <% if product.favorited_by?(current_customer) %>
                      <%= link_to customers_product_favorites_path(product), method: :delete do %>
                        <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                        <%= product.favorites.count %>
                      <% end %>
                    <% else %>
                      <%= link_to customers_product_favorites_path(product), method: :post do %>
                        <i class="fa fa-heart-o" aria-hidden="true"></i>
                        <%= product.favorites.count %>
                      <% end %>
                    <% end %>
                  <% else %>
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                      <%= product.favorites.count %>
                    <% end %>
                  </div>
                  <div class="product_price1"><%= product.name %><br></div>
                  <p class="product_price2"><%= product.price_with_tax(product.price) %>円</p><br>
                </div>
                <% end %>
             </div>
           </div>
         <% end %>
     <%= link_to "もっと見る>>>", "/customers/products/", class:"more" %>
     <%= flash[:error] %>
     </div>
     </div>
  </div>
</div>