config/routes.rb
Rails.application.routes.draw do




  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'searchs/search'
  root 'customers/products#top'
  get 'customers/products/about' => 'customers/products#about'
  get 'customers/products/favorite' => 'customers/products#favorite'

  get 'customers/mypage' => 'customers#mypage'
  get 'customers/withdraw' => 'customers#withdraw'
  put 'customers/withdraw' => 'customers#withdraw_update'
  get 'customers/fix' => 'customers#fix'
  patch 'customers/fix' => 'customers#fix_update'
  put 'customers/fix' => 'customers#fix_update'



  namespace :customers do
    resources :products, only: [:index, :show] do
      resources :post_comments, only: [:create, :destroy] #do~end
      resource :favorites, only:[:create, :destroy]
    end
    resources :product_genres, only: [:show]
    resources :cart_products, only: [:index, :update, :destroy, :create]# showをindexに変更
    delete 'cart_products' => 'cart_products#destroy_all', as:'destroy_all'

    get 'order_lists/input' => 'order_lists#input'# 順番変更とcustomers/削除
    get 'order_lists/confirm' => 'order_lists#confirm'# 追加
    get 'order_lists/thanks' => 'order_lists#thanks'# 順番変更とcustomers/削除
    resources :order_lists, only: [:index, :show, :create]# 順番変更

    resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]

  end

    get 'admins/searchs' => 'admins/searchs#search'

  namespace :admins do
    get 'top' => 'order_lists#top'

    resources :customers, only: [:index, :show, :edit, :update]

    resources :order_lists, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    resources :products, only: [:index, :show, :edit, :update, :create, :new]

    resources :product_genres, only: [:index, :edit, :update, :create]

    resources :payment_methods, only: [:index, :edit, :update, :create]

    resources :postages, only: [:index,:edit, :update, :create]
  end

end

app/models/postage.rb
class Postage < ApplicationRecord
	validates :cost, presence: true
end

app/controllers/admins/postages_controller.rb
class Admins::PostagesController < ApplicationController

	before_action :authenticate_admin!

	def index
		@postages = Postage.all
		@postage_new = Postage.new
	end

	def edit
		@postage = Postage.find(params[:id])
	end

	def update
		@postage = Postage.find(params[:id])
		if @postage.update(postage_params)
			redirect_to admins_payment_methods_path
		else
			render :edit
		end
	end

	def create
		@postage_new = Postage.new(postage_params)
		@postage_new.save
		redirect_to admins_payment_methods_path
	end

	private
	def postage_params
		params.require(:postage).permit(:cost)
	end

end

app/helpers/admins/postages_helper.rb
module Admins::PostagesHelper
end

app/views/admins/postages/edit.html.erb
<div class="midasi">
	<h3 class="midasitext">送料変更</h3>
</div>

<%= form_for @postage, url: admins_postage_path(@postage.id) do |f| %>
			<%= f.label :送料 %>
			<%= f.text_field :cost %>円
			<%= f.submit '変更' %>
<% end %>

app/views/admins/postages/index.html.erb
<div class="midasi">
	<h3 class="midasitext">支払い方法・送料</h3>
</div>

<div class="genre_form">
	<%= form_for @postage_new, url: admins_postages_path do |f| %>
		<%= f.label :送料 %>
		<%= f.text_field :cost %>
  		<%= f.submit '設定' %>
  	<% end %>
</div>
<div class="genrelists">
	<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>送料</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @postages.each do |postage| %>
		<tr>
			<td><%= postage.cost %></td>
			<td><div class="btn btn-primary active"><%= link_to "編集", edit_admins_postage_path(postage.id) %></div></td>
		</tr>
		<% end %>
	</tbody>
	</table>
</div>