config/routes.rb
Rails.application.routes.draw do




  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'searchs/search'
  root 'customers/products#top'
  get 'customers/products/about' => 'customers/products#about'
  get 'customers/products/favorite' => 'customers/products#favorite'

  get 'customers/mypage' => 'customers#mypage'
  get 'customers/withdraw' => 'customers#withdraw'
  put 'customers/withdraw' => 'customers#withdraw_update'
  get 'customers/fix' => 'customers#fix'
  patch 'customers/fix' => 'customers#fix_update'
  put 'customers/fix' => 'customers#fix_update'



  namespace :customers do
    resources :products, only: [:index, :show] do
      resources :post_comments, only: [:create, :destroy] #do~end
      resource :favorites, only:[:create, :destroy]
    end
    resources :product_genres, only: [:show]
    resources :cart_products, only: [:index, :update, :destroy, :create]# showをindexに変更
    delete 'cart_products' => 'cart_products#destroy_all', as:'destroy_all'

    get 'order_lists/input' => 'order_lists#input'# 順番変更とcustomers/削除
    get 'order_lists/confirm' => 'order_lists#confirm'# 追加
    get 'order_lists/thanks' => 'order_lists#thanks'# 順番変更とcustomers/削除
    resources :order_lists, only: [:index, :show, :create]# 順番変更

    resources :shipping_addresses, only: [:index, :edit, :update, :create, :destroy]

  end

    get 'admins/searchs' => 'admins/searchs#search'

  namespace :admins do
    get 'top' => 'order_lists#top'

    resources :customers, only: [:index, :show, :edit, :update]

    resources :order_lists, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    resources :products, only: [:index, :show, :edit, :update, :create, :new]

    resources :product_genres, only: [:index, :edit, :update, :create]

    resources :payment_methods, only: [:index, :edit, :update, :create]

    resources :postages, only: [:index,:edit, :update, :create]
  end

end

app/views/layouts/_sidebar.html.erb
<div class="col-xs-2">
  <div class="sidebar">

	  <h3 class="genre-title">ジャンル</h3>
	  <% genres.each do |genre| %>
	  <div class="genre-name"><a href="<%=  customers_product_genre_path(genre.id) %>"><%= genre.genre %></a></div>
	  <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NC</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- <script src="t.min.js"></script> -->
    <!-- <script src="t.min.js"></script> -->
  </head>

<body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <% if admin_signed_in? %>
            <%= link_to image_tag("nagano4.jpg", size:'260x83'), admins_top_path %>
          <% else %>
            <%= link_to image_tag("nagano4.jpg", size:'260x83'), "/" %>
          <% end %>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if customer_signed_in? %>
              <li><%= link_to 'アバウト', customers_products_about_path, class:"fas fa-cookie-bite" %></li>
              <li><%= link_to 'マイページ', customers_mypage_path, class:"fas fa-user-cog" %></li>
              <li><%= link_to '商品一覧', 'http://localhost:3000/customers/products/', class:"fas fa-cookie" %></li>
              <li><%= link_to 'カート', customers_cart_products_path, class:"fas fa-shopping-cart" %></li>
              <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class:"fas fa-sign-out-alt" %></li><!-- 変更 -->
            <% elsif admin_signed_in? %>
              <li><%= link_to '商品一覧', admins_products_path, class:"fas fa-cookie" %></li>
              <li><%= link_to '会員一覧', admins_customers_path, class:"fas fa-users" %></li>
              <li><%= link_to '注文履歴一覧', admins_order_lists_path, class:"fas fa-align-left" %></li>
              <li><%= link_to 'ジャンル一覧', admins_product_genres_path, class:"fas fa-ice-cream" %></li>
              <li><%= link_to '支払い関連', admins_payment_methods_path, class:"fas fa-ice-cream" %></li>
              <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"fas fa-sign-out-alt" %></li>
            <% else %>
              <li><%= link_to 'アバウト', customers_products_about_path, class:"fas fa-cookie-bite" %></li>
              <li><%= link_to '商品一覧', customers_products_path, class:"fas fa-cookie" %></li>
              <li><%= link_to '会員登録', '/customers/sign_up', class:"fas fa-user-plus" %></li>
              <li><%= link_to 'ログイン', new_customer_session_path, class:"fas fa-sign-in-alt" %></li>
            <% end %>
            <% if admin_signed_in? %>
              <nav class="search_form">

              <%= form_tag(admins_searchs_path,:method => 'get') do %>
    <%= select_tag(:option, options_for_select([["会員", "1"],["商品","2"]]))%>
    <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :name => nil, class: 'search-btn' %>
              </nav>
              <% end %>

            <% else %>
              <% if customer_signed_in? %>
            <nav class="hello_name">
              <p class="hello"><%= current_customer.name_sei %><%= current_customer.name_mei %>さんHello!今日も素敵だね<i class="fas fa-kiss-wink-heart"></i></p>
            </nav>
             <% end %>
            <% end %>

          </ul>
        </nav>

      </div>
    </header>

    <div class="container">
      <div class="main">
        <%= yield %>
        <p id="notice"><%= notice %></p>
      </div>
    </div>
  </body>
</html>